add release 1-31-0 blog post draft
conan-io/conan-io.github.io pull request #155
Opened 2020-11-04 07:43 UTC by solvingj

2020-11-04 18:01 UTC, memsharded requested changes
Please put tomorrow Thursday 5th date

2020-11-04 18:01 UTC, memsharded commented on _posts/2020-11-03-New-conan-release-1-31.markdown
> +This release contains another part of that effort which is the new `MsBuildCmd`
It is not called ``MsBuildCmd``, it is the same ``MSBuild()`` name, but internally it is a new class. This is an attempt to help to migrate to toolchains without changing this name too.

2020-11-04 18:55 UTC, solvingj commented on _posts/2020-11-03-New-conan-release-1-31.markdown
> +`conan_export.tgz` and `conan_source.tgz` in the local cache after it is done
Ok, fixing, didn't realize tat.

2020-11-04 18:57 UTC, solvingj commented on _posts/2020-11-03-New-conan-release-1-31.markdown
> +This release contains another part of that effort which is the new `MsBuildCmd`
Ok, I almost asked about it but figured we would address it today.

2020-11-05 12:44 UTC, danimtb approved these changes

2020-11-05 12:44 UTC, danimtb commented on _posts/2020-11-05-New-conan-release-1-31.markdown
> +How is this an optimization? Well buckle up because this is a long and sordid
I feel this whole explanation about this feature regarding compression and decompression is a bit lengthy and I believe the user will be more interested in the consequences than in the whole explanation. However, reading the whole blogpost, it fits with the following explanations, and, as we don't have much to talk about, I am fine with it.

2020-11-05 13:05 UTC, merged