add release 1.37 post
conan-io/conan-io.github.io pull request #191
Opened 2021-06-09 18:14 UTC by solvingj

2021-06-09 20:58 UTC, memsharded approved these changes

2021-06-10 08:01 UTC, danimtb approved these changes

2021-06-10 08:55 UTC, danimtb requested changes
We need to add a highlight in this post about the new `conancenter` remote. This is important as this is no longer a BETA remote (https://blog.conan.io/2021/04/23/New-Conan-Center-url.html) but actually the official remote for conan center with recipes only coming from conan-center-index (https://github.com/conan-io/conan-center-index).

Also, the old `conan-center` (bintray) remote will stop syncing packages from `conancenter` remote on June 1st. Eventually, `conan-center` remote will be removed as default remote in the conan client.

2021-06-10 09:11 UTC, jgsogo approved these changes

2021-06-10 09:11 UTC, jgsogo commented on _posts/2021-06-10-New-conan-release-1-37.markdown
> +which were created using `conan export-pkg` commnd, rebuilding from source is
```suggestion
which were created using `conan export-pkg` command, rebuilding from source is
```

2021-06-10 14:16 UTC, solvingj commented
@danimtb , good catch.  i added a section right at the top. please review.

2021-06-10 15:56 UTC, danimtb approved these changes

2021-06-10 15:57 UTC, jgsogo commented on _posts/2021-06-10-New-conan-release-1-37.markdown
> +"legacy" we mean packages which predate ConanCenterIndex.) Currently, copies of
```suggestion
"legacy" we mean packages which predate ConanCenterIndex). Currently, copies of
```

2021-06-10 15:57 UTC, jgsogo commented on _posts/2021-06-10-New-conan-release-1-37.markdown
> +default list of remotes, nor the physical deletion of the repository and it's
```suggestion
default list of remotes, nor the physical deletion of the repository and its
```

2021-06-10 16:00 UTC, merged