Blogpost about XRay integration with Conan
conan-io/conan-io.github.io pull request #197
Opened 2021-08-31 09:58 UTC by czoido

2021-08-31 10:13 UTC, danimtb approved these changes

2021-08-31 10:13 UTC, danimtb commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +We will create a security **policy** named *mycompany-policy* and add one rule to it. Click in *New Rule* and set *low-severity-warning* as the rule name. This rule will adjust the minimal severity t
```suggestion
We will create a security **policy** named *mycompany-policy* and add one rule to it. Click in *New Rule* and set *low-severity-warning* as the rule name. This rule will adjust the minimal severity to low (severity score under 4.0/10.0). You can set the severity warning based on predefined ranges (low, medium, high or critical) or set up a [custom CVSS Score range](https://www.jfrog.com/confluence/display/JFROG/CVSS+Scoring+in+Xray). Multiple actions can be triggered when the rule conditions are satisfied. We will add the *Notify Email* action for this rule and check what happens when uploading a package with known security issues.
```

2021-08-31 10:13 UTC, danimtb commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +Now that we added the **policy** and connected the Conan repository to that **policy** with a **watch**, it is time to test it with the Conan client. We upload a Conan package that's affected by some
IMO would it be interesting to know where XRay is getting the vulnerability information from. Is there something in their documentation that we can link here?

2021-08-31 10:26 UTC, memsharded approved these changes
Fantastic!

2021-08-31 10:26 UTC, memsharded commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +new repository, we will add it to the Conan local client using *conan remote add* and *conan user*
Maybe add a link to our own docs too?

2021-08-31 10:26 UTC, memsharded commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +<p class="centered">
Maybe this would be simpler to read just copying the output message in the above, the animation doesn't add much?

2021-08-31 14:14 UTC, uilianries requested changes

2021-08-31 14:14 UTC, uilianries commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +The first thing we have to define to start working with Xray is a **policy**. A **policy** is just a
```suggestion
The first thing we have to define to start working with Xray is a **policy**. A [policy](https://www.jfrog.com/confluence/display/XRAY2X/Policies) is just a
```

2021-08-31 14:14 UTC, uilianries commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +The next thing is adding a **watch**. **Watches** connect the **resources** (such as repositories or
```suggestion
The next thing is adding a **watch**. The [Watches](https://www.jfrog.com/confluence/display/XRAY2X/Watches) connect the **resources** (such as repositories or
```

2021-08-31 14:14 UTC, uilianries commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +$ conan upload openssl/1.1.1h --all -c -r test-repo
```suggestion
$ conan upload openssl/1.1.1h@ --all -c -r test-repo
```

2021-08-31 14:14 UTC, uilianries commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +$ conan upload openssl/1.1.1h --all -c -r test-repo
bikeshedding, but keeps same pattern as install command

2021-08-31 14:14 UTC, uilianries commented on _posts/2021-09-15-Conan-XRay-Integration.markdown
> +$ conan remove openssl/1.1.1h -f # to force downloading from the server
```suggestion
$ conan remove openssl/1.1.1h@ -f # to force downloading from the server
```

bikeshedding, but keeps same pattern.

2021-09-01 06:31 UTC, lasote approved these changes
👍

2021-09-01 11:42 UTC, uilianries approved these changes

2021-09-06 18:23 UTC, uilianries approved these changes

2021-09-07 09:50 UTC, merged