- blog-post about M1
conan-io/conan-io.github.io pull request #200
Opened 2021-09-08 13:13 UTC by SSE4

2021-09-10 14:37 UTC, jgsogo reviewed
Some suggestions trying to help with the content structure. Then, we can enter more into details.

2021-09-10 14:37 UTC, jgsogo commented on _posts/2021-09-06-m1.markdown
> +
Maybe this is a good place to say a word about Conan settings and package IDs:

> In order to start creating your packages for M1, you don't need anything special. Conan already provides build-helpers and tools that adapted for this new architecture. You only need to provide proper inputs to creation commands, basically a host profile with the following settings:
> 
> ```ini
> [settings]
> os=Macos
> arch=armv8
> ...
> ```
> 
> Conan will generate the binaries for this new architecture and you can safely upload them to your own Artifactory, Conan will compute a different packageID because of the new settings value.
> 
> Of course, your building machine need to provide the tooling required for this build, but any updated Macos should do work.

Then, we can explain the architecture naming and the confusion, but we already know that Conan will use `armv8`, these are the details about why.

2021-09-10 14:37 UTC, jgsogo commented on _posts/2021-09-06-m1.markdown
> +```
Better to use always full profiles, this blog post can be read (and tried) by people running Windows/Linux where the _default_ profile is not a Macos one.

2021-09-10 14:37 UTC, jgsogo commented on _posts/2021-09-06-m1.markdown
> +## Cross-building
Now let's start with the ConanCenter-related part. This is just an example, please reword:

> ## Apple M1 binaries in ConanCenter
> 
> Starting on XXXXX we are building Apple M1 binaries in ConanCenter. We want to help the community of developers that want to target their applications to this new architecture and are currently using Conan to manage their dependencies. 
> 
> As said before, generating binaries for Apple M1 using Conan is really straightforward, we just need to use a profile for Macos-armv8 and build our packages.
> 
> ### Cross-building
> 
> Some packages declare build-requires and they need to be executed while building the libraries. We could have connected to the CI system an M1 machine, it would have been easier, but we decided to cross-build these package using the Macos machines we were already using. 
> 
> We knew it would be harder, because it was the first configuration of ConanCenter that we would generate using cross-compilation, but at the same time the effort would pay off because the quality of recipes will increase and support for other cross-building scenarios would be easier (iOS, Android,...).
> 
> These are some of the most common adaptations we needed to do the recipes:

Also, we need to add some warning here:

_"Take into account that ConanCenter uses at the time of writing Conan v1.38, new build-helpers were not mature enough to be used in recipes. Some of the following fixes will no longer apply with the new integrations and we really expect to be able to simplify the recipes once they are available."_

2021-09-12 09:24 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +
In order to start creating your packages for M1, you don't need anything special. Conan already provides
 build-helpers and tools that adapted for this new architecture. You only need to provide proper inputs
 to creation commands, basically a host profile with the following settings:

```bash
$ cat ~/.conan/profiles/m1

[settings]
os=Macos
arch=armv8
...
```

Conan will generate the binaries for this new architecture and you can safely upload them to your own
 Artifactory, Conan will compute a different packageID because of the new settings value.

Of course, your building machine need to provide the tooling required for this build, but any
 updated Macos should do work.

2021-09-12 09:29 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +## Cross-building
```suggestion
## Apple M1 binaries in ConanCenter

Starting on [24-May-2021 - 15:59 CEST](https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#24-may-2021---1559-cest)
 we are building Apple M1 binaries in ConanCenter. We want to help the community
 of developers that want to target their applications to this new architecture and
  are currently using Conan to manage their dependencies.

As said before, generating binaries for Apple M1 using Conan is really straightforward, we
 just need to use a profile for Macos-armv8 and build our packages.

## Cross-building

Some packages declare their build-requires and they need to be executed while
 building the libraries. We could have connected to the CI system an M1 machine,
 it would have been easier, but we decided to cross-build these package using the
 existing Macos machines we were already using.

We knew it would be harder, because it was the first configuration of ConanCenter
 that we would be generated using the cross-compilation, but at the same time
 the effort would pay off because the quality of recipes will increase and support
 for other cross-building scenarios would be easier (iOS, Android, Emscripten, Raspberry Pi, etc).

These are some of the most common adaptations we needed to do the recipes:
```

2021-09-12 09:30 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +```
added your proposed paragraph with some re-wording

2021-09-12 09:30 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +## Cross-building
added your proposed paragraph with some re-wording

2021-09-12 09:31 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +
added your proposed paragraph with some re-wording

2021-09-12 09:32 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + updated Macos should do work.
```suggestion
 updated Macos should do a work.

```

2021-09-12 09:34 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + Artifactory, Conan will compute a different packageID because of the new settings value.
```suggestion
 [Artifactory](https://jfrog.com/artifactory/), Conan will compute a different
 [package ID]*https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html(because of the new settings value.
```

2021-09-12 09:34 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + [package ID]*https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html(because of the new settings value.
```suggestion
 [package ID](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) (because of the new settings value.
```

2021-09-12 09:35 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + updated Macos should do a work.
```suggestion
 updated macOS should do a work.
```

2021-09-12 09:36 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +bash
```suggestion
```bash
```

2021-09-12 09:36 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +...
```suggestion
...```
```

2021-09-12 09:36 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +$ conan install -s arch=armv8
```suggestion
cat ~/.conan/profiles/m1
[settings]
os=Macos
arch=armv8
...
```

2021-09-12 09:37 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + just need to use a profile for Macos-armv8 and build our packages.
```suggestion
 just need to use a profile for macOS/ARMv8 and build our packages.
```

2021-09-12 09:38 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +Take into account that ConanCenter uses at the time of writing Conan v1.38,
```suggestion
Take into account that ConanCenter uses at the time of writing [Conan v1.38](https://docs.conan.io/en/latest/changelog.html#jun-2021),
```

2021-09-12 09:39 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + new build-helpers were not mature enough to be used in recipes. Some of the
```suggestion
 new [build-helpers](https://docs.conan.io/en/latest/reference/build_helpers.html) were not mature enough to be used in recipes. Some of the
```

2021-09-12 09:39 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + expect to be able to simplify the recipes once they are available
```suggestion
 expect to be able to simplify the recipes once they are available.
```

2021-09-13 15:39 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +We were asked several times to provide some ARM binaries for ConanCenter, and finally, they are there.
Not generic ARM binaries, they are not there in the general case, just the Apple ARM M1 binaries, or at least Apple OSX ARM binaries.

2021-09-13 15:39 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> + updated macOS should do a work.
```suggestion
 updated macOS should do the job.
```

2021-09-13 15:39 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +```bash
Identical, repeated profile as above, probably can be skipped.

2021-09-13 15:39 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +with the extremely simple `m1` profille:
```suggestion
with the extremely simple `m1` profile:
```

2021-09-13 15:39 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +if self.settings_build.os == "Windows":
This will raise if not 2 profiles are defined, so this should be avoided directly in ConanCenter without a check for ``settings_build`` definition.

2021-09-13 15:39 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
Doesn't seem correct. With 2 profiles, the environment ``deps_env_info`` comes from the build context.

2021-09-13 16:40 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +if self.settings_build.os == "Windows":
yes, I think you're right

2021-09-13 16:42 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +if self.settings_build.os == "Windows":
```suggestion
@property
def _settings_build(self):
    return self.settings_build if hasattr(self, "settings_build") else self.settings

if self._settings_build.os == "Windows":
```

2021-09-13 16:42 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
that's copied from conan docs. if so, it has to be fixed in docs.

2021-09-13 16:43 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +We were asked several times to provide some ARM binaries for ConanCenter, and finally, they are there.
```suggestion
We were asked several times to provide some macOS ARM binaries for ConanCenter, and finally, they are there.
```

2021-09-13 16:43 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +We were asked several times to provide some ARM binaries for ConanCenter, and finally, they are there.
let's add some clarification then

2021-09-13 16:44 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +```bash
okay, let's remove the second occurrence of the same profile

2021-09-13 16:45 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +```
```suggestion
```

2021-09-13 16:45 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + so consumers will have to specify `arch=armv8` in their profiles or command lines:
```suggestion
 so consumers will have to specify `arch=armv8` in their profiles or command lines.
```

2021-09-13 16:46 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-env-info
```
Note

If using the experimental feature with different context for host and build, 
this attribute will contain only information from packages in the build context.
```

2021-09-20 09:06 UTC, SSE4 commented
@memsharded @jgsogo if there are no more concerns, please approve and let's merge. all your comments were already addressed.

2021-09-20 11:24 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
I still think this is not right: the documentation is saying:

- Packages in build context define ``deps_env_info``

You are saying:

- Packages in the build context can no longer use ``deps_env_info``, and can only use ``user_info_build``.

So this still seems contradictory.

2021-09-20 11:29 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
@jgsogo can you clarify then why this could be necessary in recipes?
```
    @property
    def _user_info_build(self):
        return getattr(self, "user_info_build", None) or self.deps_user_info
```
as per Diego, it seems like contradictory.

2021-09-20 11:33 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
checking again, I found it:
```
If using the experimental feature with different context for host and build, this attribute will contain only information from packages in the host context. Use user_info_build to access information from packages that belong to build context.
```
https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-user-info
so this doesn't appear to be contradictory. it's contradictory in docs, because one paragraph says it only provides build context, but another one says it provides only host context.
so again, I think it's docs issue.

2021-09-20 11:38 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
This is the current behavior:

```python
            if not using_build_profile:  # Do not touch anything
                conan_file.deps_user_info[n.ref.name] = n.conanfile.user_info
                conan_file.deps_cpp_info.add(n.ref.name, dep_cpp_info)
                conan_file.deps_env_info.update(n.conanfile.env_info, n.ref.name)
            else:
                if n in transitive or n in br_host:
                    conan_file.deps_user_info[n.ref.name] = n.conanfile.user_info
                    conan_file.deps_cpp_info.add(n.ref.name, dep_cpp_info)
                else:
                    conan_file.user_info_build[n.ref.name] = n.conanfile.user_info
                    env_info = EnvInfo()
                    env_info._values_ = n.conanfile.env_info._values_.copy()
                    # Add cpp_info.bin_paths/lib_paths to env_info (it is needed for runtime)
                    env_info.DYLD_LIBRARY_PATH.extend(dep_cpp_info.lib_paths)
                    env_info.DYLD_FRAMEWORK_PATH.extend(dep_cpp_info.framework_paths)
                    env_info.LD_LIBRARY_PATH.extend(dep_cpp_info.lib_paths)
                    env_info.PATH.extend(dep_cpp_info.bin_paths)
                    conan_file.deps_env_info.update(env_info, n.ref.name)
```

So it seems that what is explained in the blog post is not correct. If the docs needs a fix, lets fix the docs too.

2021-09-20 11:43 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
well, if it's incorrect - it will have even more consequences. it means the workaround we currently apply in numerous recipes is incorrect. and they all have to be fixed.

2021-09-20 13:13 UTC, uilianries commented on _posts/2021-09-06-m1.markdown
> +We also strongly encourage all the consumers to migrate their cross-building scenarios to the two profiles approach whenever possible.
```suggestion
We strongly encourage authors to remove `os_build` and `arch_build` from their recipes.
We also strongly encourage all the consumers to migrate their cross-building scenarios to the two profiles approach whenever possible. The reason is because build context allows better compatibility using build requirements, avoiding separated packages for installer and tooling.
```

Trying to explain a little about the reason behind for migrating from os_build/arch_build to build context

2021-09-20 13:13 UTC, uilianries commented on _posts/2021-09-06-m1.markdown
> +and the first phase usually runs on the Linux machine, thus, package ID computation for macOS M1 profile is done on Linux x86 build machine.
```suggestion
And the first phase usually runs on the Linux machine, thus, package ID computation for macOS M1 profile is done on Linux x86 build machine.
```

2021-09-20 13:13 UTC, uilianries commented on _posts/2021-09-06-m1.markdown
> +  [os.name](https://docs.python.org/3/library/os.html) or similar facilities to detect the build platform.
```suggestion
* [tools.OSInfo](https://docs.conan.io/en/latest/reference/tools.html#tools-osinfo-and-tools-systempackagetool),
* [platform.system](https://docs.python.org/3/library/platform.html),
* [os.name](https://docs.python.org/3/library/os.html) or similar facilities to detect the build platform.
```

2021-09-20 13:13 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
@jgsogo please have a look when possible

2021-09-20 13:15 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +$ cat ~/.conan/profiles/m1
yes, more portable as well

2021-09-20 13:17 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +with the extremely simple `m1` profile:
they might make some sense, especially in case someone will try to build from Linux/Windows. let's update

2021-09-20 13:19 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +arch=armv8
```suggestion
arch=armv8
os=Macos
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
```

2021-09-20 13:29 UTC, czoido commented on _posts/2021-09-06-m1.markdown
> +...```
```suggestion
...
```
```

2021-09-20 13:31 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +...```
```suggestion
...
```
```

2021-09-20 13:33 UTC, jgsogo commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
Those are different variables.

`deps_env_info` contains information only from dependencies in the _build_ context, as stated here in the docs (and match sources): https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deps-env-info

And then, there is the _issue_ (and workaround) in ConanCenter to retrieve information from the `self.user_info` defined in a recipe. The compatible way to do it for one and two profiles is:

```
    @property
    def _user_info_build(self):
        return getattr(self, "user_info_build", None) or self.deps_user_info
```

which can be _translated_ to something like: _"to get information from the `self.user_info` defined in one of the build-requirements, you need to use `user_info_build` if available (two profiles), or fallback to `deps_user_info` that contain the information from all the requirements"_.

That's all. In some sense, all of you are right... but the blogpost contains one mistake (I follow in next comment).

2021-09-20 13:36 UTC, jgsogo commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
Nevertheless, IMHO, I would remove this section from the blogpost. It enters very specific details that are not interesting for the feature or announcement.

I did a review about the structure and I was waiting for some other to comment about the structure too. Then we can go into the content and details, but first better to agree on the history, sections, pace,...

2021-09-20 13:37 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + [package ID](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) (because of the new settings value.
```suggestion
 [package ID](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) (because of the new settings value).
```

2021-09-20 13:38 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +* `ARMv8-A` - refers to the *A* (Application) profile of the ARM architecture, specifically. Other profiles are *R* (Real-time) and *M* (Microcontroller).
```suggestion
* `ARMv8-A` - refers to the *A* (Application) profile of the ARM architecture, specifically. Other profiles are *R* (Real-time) and *M* (Microcontroller). Or, `ARMv8-R` and `ARMv8-M`, respectively.
```

2021-09-20 13:39 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +* `A64` - refers to the instruction set for the `AArch64` execution state.
```suggestion
* `A64` - refers to the instruction set for the `AArch64` execution state. The name is rarely used outside of the ARM documentation.
```

2021-09-20 13:39 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +* `ARM64` unofficial (e.g. not used in official ARM documents) but extremely popular name synonymous to the `AArch64`. Apple software (e.g. [Xcode](https://developer.apple.com/xcode/) and other devel
```suggestion
* `ARM64` - an unofficial (e.g. not used in the official ARM documents) but extremely popular name synonymous to the `AArch64`. Apple software (e.g. [Xcode](https://developer.apple.com/xcode/) and other developer tools) use this naming. Also, used by many Linux distros.
```

2021-09-20 13:41 UTC, memsharded commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
Agree with @jgsogo.

2021-09-20 13:42 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
I think structure is already agreed. at least no-one had any objections, except you suggested two additional paragraphs which are already there.

2021-09-20 13:44 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +### deps_cpp_info, deps_env_info and deps_user_info contain information only from the host context
okay, let's remove this section altogether then.

2021-09-20 13:45 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + existing Macos machines we were already using.
```suggestion
 existing macOS machines we were already using.
```

2021-09-20 13:46 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + building the libraries. We could have connected to the CI system an M1 machine,
```suggestion
 building the libraries. We could have connected to the CI system a M1 machine,
```

2021-09-20 13:47 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +And the first phase usually runs on the Linux machine, thus, package ID computation for macOS M1 profile is done on Linux x86 build machine.
```suggestion
And the first phase usually runs on the Linux machine, thus, package ID computation for macOS M1 profile is done on Linux x86-64 build machine.
```

2021-09-20 14:04 UTC, czoido commented on _posts/2021-09-06-m1.markdown
> +Starting on [24-May-2021 - 15:59 CEST](https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#24-may-2021---1559-cest)
```suggestion
From [24 May 2021](https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#24-may-2021---1559-cest),
```

2021-09-20 14:09 UTC, czoido commented on _posts/2021-09-06-m1.markdown
> +
I would use this section to make a brief summary of the whole post and give some general data... that we will use cross-building, that we are going to explain how to adapt recipes...

2021-09-20 14:16 UTC, czoido commented on _posts/2021-09-06-m1.markdown
> +### confusion about the architecture naming
```suggestion
### Confusion about the architecture naming
```

2021-09-20 14:26 UTC, czoido commented on _posts/2021-09-06-m1.markdown
> +## Apple M1 binaries in ConanCenter
Maybe I would change this title to something like: _How we create Apple M1 binaries in ConanCenter using cross-building_ or something like that. Removing the _Cross-building_ title above and make a new section like _Adapting existing recipes in ConanCenter for cross-building_ or something like that... and under that all the sections about the fixes that may be needed...

2021-09-20 15:39 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +## Apple M1 binaries in ConanCenter
```suggestion
## How do we create Apple M1 binaries in ConanCenter using cross-building
```

2021-09-20 15:39 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +## Cross-building
```suggestion
## Adapting existing recipes in ConanCenter for cross-building
```

2021-09-20 15:40 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +## Apple M1 binaries in ConanCenter
thanks, I've changed titles according to your suggestions

2021-09-20 15:41 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +We were asked several times to provide some macOS ARM binaries for ConanCenter, and finally, they are there.
```suggestion
We were asked several times to provide some macOS ARM binaries for ConanCenter, and finally, they are there.
The article describes the following aspects:
* general information about Apple M1
* how Apple M1 binaries are created in ConanCenter
* how to adapt existing recipes to support cross-building to Apple M1
  
```

2021-09-20 15:42 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +
thanks, I've added the summary to the section

2021-09-20 16:05 UTC, tapia requested changes

2021-09-20 16:05 UTC, tapia commented on _posts/2021-09-06-m1.markdown
> +There are several important side-effects to the recipes because of the movement to the two profiles approach:
Better "switch" than "movement", I think.

2021-09-20 16:09 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +title: "ConanCenter: Apple M1 binaries are generated"
well, M1 is not an architecture name by itself, it's a name of SoC. we may say ARMv8 to be correct, or rephrase it differently.

2021-09-20 16:10 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +  (MacBook Air, MacBook Pro, Mac Mini, and iMac) are already available shipping with M1 onboard. We expect the popularity and need for
```suggestion
  (MacBook Air, MacBook Pro, Mac Mini, and iMac) are already available with M1 processors. We expect the popularity and need for
```

2021-09-20 16:13 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + build-helpers and tools that adapted for this new architecture. You only need to provide proper inputs
well, I'd say all 3 are correct, depends on what do you want to say:
`tools that are adapted` is passive voice
`tools adapted` is active voice (past simple)
`tools that adapted` is same as `tools adapted` but rereferring to `tools` that were already known/mentioned before.
referring to @jgsogo as an original author of the paragraph

2021-09-20 16:14 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + [package ID](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) (because of the new settings value).
```suggestion
 [package ID](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) because of the new settings value.
```

2021-09-20 16:14 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +* `ARMv8` - refers to the new version of the ARM architecture. It includes two execution states, `AArch32` and `AArch64`, and corresponding instruction sets for them.
```suggestion
* `ARMv8` - refers to the new version of the ARM architecture. It includes two execution states, `AArch32` and `AArch64`, and the corresponding instruction set for each of them.
```

2021-09-20 16:16 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + that we would be generated using the cross-compilation, but at the same time
```suggestion
We knew it would be harder, because it is the first configuration of ConanCenter
 that will be generating cross-compiled binaries, but at the same time
```

2021-09-20 16:16 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + for other cross-building scenarios would be easier (iOS, Android, Emscripten, Raspberry Pi, etc).
```suggestion
 the effort would pay off because the quality of recipes will increase and
 adding new cross-building scenarios in the future will be easier (iOS, Android, Emscripten, Raspberry Pi, etc).
```

2021-09-20 16:17 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + new [build-helpers](https://docs.conan.io/en/latest/reference/build_helpers.html) were not mature enough to be used in recipes. Some of the
```suggestion
Take into account that the Conan version used in ConanCenter at the time of adding the M1 support was [1.38](https://docs.conan.io/en/latest/changelog.html#jun-2021),
 and the new [build-helpers](https://docs.conan.io/en/latest/reference/build_helpers.html) were not mature enough to be used in production recipes.
```

2021-09-20 16:18 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + might not be prepared for that, so recipe authors may decide to skip M1 support for a while:
```suggestion
This is the very first time we support actual cross-building in ConanCenter, so many recipes or
 libraries might not be prepared for that. If you need it, you can skip M1 support for a while:
```

2021-09-20 16:19 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +Since Intel Mac machines we currently use on CI won't be able to execute the ARM code, the following extra check is now required for the
```suggestion
Since the Intel Mac machines we currently use on CI won't be able to execute the ARM code, the following extra check is now required for the
```

2021-09-20 16:19 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +M1 is also the very first case we adopted [two profiles](https://docs.conan.io/en/latest/devtools/build_requires.html?build-and-host-contexts)
```suggestion
This is also the very first time we use the [two profiles model](https://docs.conan.io/en/latest/devtools/build_requires.html?build-and-host-contexts)
```

2021-09-20 16:19 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +There are several important side-effects to the recipes because of the movement to the two profiles approach:
```suggestion
There are several important side-effects to the recipes because of the switch to the two profiles approach:
```

2021-09-20 16:25 UTC, czoido commented on _posts/2021-09-06-m1.markdown
> +title: "ConanCenter: Apple M1 binaries are generated"
I also think we should rephrase the title to something more meaningful... 
Maybe something like this?
New Apple M1 binaries: Adapting ConanCenter recipes for cross-building (I don't love the this title, maybe we can come up with something better...)

2021-09-20 16:28 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +  as this is going to be a default mode in [Conan 2.0](https://docs.conan.io/en/latest/conan_v2.html).
@jgsogo what would you say is the main factors? I see it like:
- both host and build context now have the full set of settings (previously, build profile was incomplete and only contained `arch_build`/`os_build`, but e.g. no `os.version`)
- allow to have the same package but for different architectures in graph (e.g. x86 `protoc.exe` + ARM `libprotobuf.so`)

I think there were many other significant limitations with single profile, I just don't have them on mind.

2021-09-21 07:16 UTC, tapia commented on _posts/2021-09-06-m1.markdown
> + build-helpers and tools that adapted for this new architecture. You only need to provide proper inputs
I'm not sure if the last one. Anyway, "Conan already provides build-helpers and tools adapted for this new architecture" looks like the simplest way to put it.

2021-09-21 07:18 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + build-helpers and tools that adapted for this new architecture. You only need to provide proper inputs
okay, let's change it that way

2021-09-21 07:19 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> + build-helpers and tools that adapted for this new architecture. You only need to provide proper inputs
```suggestion
 build-helpers and tools adapted for this new architecture. You only need to provide proper inputs
```

2021-09-21 07:31 UTC, tapia commented on _posts/2021-09-06-m1.markdown
> +title: "ConanCenter: Apple M1 binaries are generated"
Everybody will know what you're talking about reading the title, and you're explaining the confusion between the different names inside the post. I think you're safe. But if you want to be (overly) precise, remove the reference to the architecture: "Apple M1 support added to ConanCenter".

@czoido The title should be short and clear. I wouldn't mention cross-building in the title. That's a ConanCenter internal: interesting to read, but not really the point of the post.

2021-09-21 07:32 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +title: "ConanCenter: Apple M1 binaries are generated"
okay, let's do `Apple M1 support added to ConanCenter` then.

2021-09-21 07:33 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +meta_title: "ConanCenter: Apple M1 binaries are generated"
```suggestion
meta_title: "Apple M1 support added to ConanCenter"
```

2021-09-21 07:33 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +title: "ConanCenter: Apple M1 binaries are generated"
```suggestion
title: "Apple M1 support added to ConanCenter"
```

2021-09-21 07:48 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +  as this is going to be a default mode in [Conan 2.0](https://docs.conan.io/en/latest/conan_v2.html).
from @jgsogo :
```
I would change the link to https://github.com/conan-io/tribe/blob/main/design/023-use_always_build_profile.md, this is not the blogpost to explain or justify it.


If any justification is needed, it should come from Conan v2 documents (tribe, docs, issues, PRs,…), on the conan-center side we just echo it
```
@tapia are you okay with that? I think we can't explain everything in the blog post, providing a link to the explanation should be enough.

2021-09-21 09:53 UTC, tapia commented on _posts/2021-09-06-m1.markdown
> +  as this is going to be a default mode in [Conan 2.0](https://docs.conan.io/en/latest/conan_v2.html).
Yep, totally fine by me :-)

2021-09-21 09:57 UTC, SSE4 commented on _posts/2021-09-06-m1.markdown
> +  as this is going to be a default mode in [Conan 2.0](https://docs.conan.io/en/latest/conan_v2.html).
```suggestion
  as this is going to be a default mode in [Conan 2.0](https://github.com/conan-io/tribe/blob/main/design/023-use_always_build_profile.md).
```

2021-09-21 10:01 UTC, tapia approved these changes

2021-09-21 10:02 UTC, merged