New post: "Conan and Conan Center: 2021 in numbers"
conan-io/conan-io.github.io pull request #211
Opened 2021-12-29 08:18 UTC by tapia

Draft post just to check the content. It's missing the updated charts.

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +2021 has been quite a busy year for Conan. We are working hard to get Conan 2.0 ready, almost 3
Almost 4 years (1.0.0 (10-January-2018))
```suggestion
2021 has been quite a busy year for Conan. We are working hard to get Conan 2.0 ready, almost 4
```

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +celebrated with our community a huge milestone: on August, Conan Center
```suggestion
celebrated with our community a great milestone: on August, Conan Center
```

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Conan is the **most used C/C++ package manager**.
Maybe clarify something in the line "after manual solutions and system package managers", or "the most used C and C++ language specific package manager"

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +installs coming from mirrors. The most popular source, though, is PyPI, the Python package index.
Need to clarify that the PyPI stats can be noisy because of mirrors and other factors. A link and capture of the screen would be nice, as this is a moving number.

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +|     | Conan | Conan Center |
A bar plot of this would be nice

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +CHART <Users evolution>
Add some further insights, like the docs is the main source of activity, that it is organic, and the average reading time (to show engagement with the site)

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +
Need to add here the Artifactory stats too, maybe aggregated? separated CE and PRO? Lets discuss

2021-12-29 09:25 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Our channel in the [CppLang slack server](https://cpplang.slack.com/), #conan, is the 2nd most
Capture screen with number, as this also moves

2021-12-29 09:47 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +2021 has been quite a busy year for Conan. We are working hard to get Conan 2.0 ready, almost 3
Awesome, I don't know how to subtract 😄

2021-12-29 09:58 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +|     | Conan | Conan Center |
Of course. @jgsogo is updating the charts, I'll add them as soon as they are ready

2021-12-29 14:23 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Conan is the **most used C/C++ package manager**.
I'm not sure about that. "Manual solutions" are not package managers, and "system package managers" are not C/C++ package managers. I think the phrasing is precise enough.

2021-12-29 14:42 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +installs coming from mirrors. The most popular source, though, is PyPI, the Python package index.
Not sure about this either. This is a marketing post to show how we're doing, not an academic paper. There's no need to give exactly correct numbers.

2021-12-29 14:56 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Our channel in the [CppLang slack server](https://cpplang.slack.com/), #conan, is the 2nd most
Done

2021-12-29 14:56 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +|     | Conan | Conan Center |
Done

2021-12-30 10:49 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +CHART <Users evolution>
Done

2021-12-30 10:50 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Conan is the **most used C/C++ package manager**.
I would still add something like ``most used (language-specific) C and C++ package manager``. Try to use ``C and C++``, not C/C++ if possible. Better be complete and clear, if people read the survey results, they should not expect Conan to be the biggest bar in the plot. @czoido feedback please?

2021-12-30 10:50 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +installs coming from mirrors. The most popular source, though, is PyPI, the Python package index.
Yes, better be as clear, exact and honest as possible. I don't want to seem we are stating that Conan got 500k installs from developers from PyPI, because that might not be the case, PyPI stats are very noisy, and we know it. This is not a marketing post, this is a report of what we know to our users.

2021-12-30 10:50 UTC, memsharded commented on _posts/2022-01-02-conan-stats-2021.markdown
> +
Ping, section for Artifactory stats?

2021-12-30 11:39 UTC, czoido commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Conan is the **most used C/C++ package manager**.
Yes, I think that a clarification would be good... like you say: "the most used C and C++ language specific package manager"  for me it's enough

2021-12-30 11:54 UTC, czoido commented on _posts/2022-01-04-conan-stats-2021.markdown
> +celebrated with our community a great milestone: on August, Conan Center
```suggestion
celebrated with our community a great milestone: in August, Conan Center
```

2021-12-30 11:57 UTC, czoido commented on _posts/2022-01-04-conan-stats-2021.markdown
> +installs coming from mirrors. The most popular source, though, is PyPI, the Python package index.
Maybe I would omit the sentence: "There are
[a lot of ways](https://conan.io/downloads.html) to install Conan, and we don't have data on
installs coming from mirrors" just a personal preference to go straight to the point but it's not important.

2021-12-30 11:59 UTC, czoido commented on _posts/2022-01-04-conan-stats-2021.markdown
> +But the true indicator of how healthy an Open Source project is, is its GitHub activity. Here are
true --> most valuable, most important... ?
```suggestion
But the true indicator of how healthy an Open Source project is in its GitHub activity. Here are
```

2021-12-30 12:00 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +
Not sure what data we should show here. The number of Artifactory instances is not a very informative number if you don't really know what Artifactory is and how is it used from a Conan perspective.

2021-12-30 12:00 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +Conan is the **most used C/C++ package manager**.
Done

2021-12-30 12:07 UTC, tapia commented on _posts/2022-01-04-conan-stats-2021.markdown
> +installs coming from mirrors. The most popular source, though, is PyPI, the Python package index.
The reason for this is to point out that the following stats are coming only from PyPI, not the rest of installers

2021-12-30 12:08 UTC, czoido commented on _posts/2022-01-04-conan-stats-2021.markdown
> +of lines to their ConanFiles.
```suggestion
When we created Conan Center in August 2019, we were trying to fill a void in our ecosystem: back 
then, the latest version of the Conan client was 1.18, so it was completely production-ready, but
we didn't have our own package repository to handle dependencies straightforwardly. We 
wanted for our users to be able to install open source libraries and tools by just adding a couple
of lines to their ConanFiles.
```

2021-12-30 12:14 UTC, czoido commented on _posts/2022-01-04-conan-stats-2021.markdown
> +    <img src="{{ site.url }}/assets/post_images/2022-01-04/data-transfer-2.png">
This figure adds conan.bintray.com to the bars, do we want this? Or just showing the conancenter data transfer?

2021-12-30 12:17 UTC, tapia commented on _posts/2022-01-02-conan-stats-2021.markdown
> +installs coming from mirrors. The most popular source, though, is PyPI, the Python package index.
Done

2021-12-30 13:30 UTC, jgsogo reviewed
I would make images big enough for the height/width, but not so big as they are now, those huge images penalize the browsing experience (maybe they also penalize indexing?).

2021-12-30 13:30 UTC, jgsogo commented on _posts/2022-01-04-conan-stats-2021.markdown
> +    <img src="{{ site.url }}/assets/post_images/2022-01-04/data-transfer-2.png">
Not sure, but at least something related to "Bintray shutdown, no legacy behind", to explain why those numbers go to zero for Bintray. maybe?

2022-01-04 13:38 UTC, memsharded requested changes
The post is still missing the Artifactory data

2022-01-13 09:50 UTC, merged